(defun vendor (library)
  (let* ((file (symbol-name library))
         (normal (concat "~/.emacs.d/vendor/" file))
         (suffix (concat normal ".el"))
         (bigeye (concat "~/.emacs.d/bigeye/" file)))
    (cond
     ((file-directory-p normal) (add-to-list 'load-path normal) (require library))
     ((file-exists-p suffix) (require library)))
    (when (file-exists-p (concat bigeye ".el"))
      (load bigeye))))